export const ADD_PLAYLISTDATA_LOADING = "ADD_PLAYLISTDATA_LOADING";
export const ADD_PLAYLISTDATA_SUCCESS = "ADD_PLAYLISTDATA_SUCCESS";
export const ADD_PLAYLISTDATA_ERROR = "ADD_PLAYLISTDATA_ERROR";

export const GET_USER_LOADING = "GET_USER_LOADING";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";