export const GET_PLAYLISTDATA_LOADING = "GET_PLAYLISTDATA_LOADING";
export const GET_PLAYLISTDATA_SUCCESS = "GET_PLAYLISTDATA_SUCCESS";
export const GET_PLAYLISTDATA_ERROR = "GET_PLAYLISTDATA_ERROR";
//
export const CREATE_PLAYLIST_LOADING = "CREATE_PLAYLIST_LOADING";
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS";
export const CREATE_PLAYLIST_ERROR = "CREATE_PLAYLIST_ERROR";
//
export const SET_ACTIVE_PLAYLIST = "SET_ACTIVE_PLAYLIST"
//
export const GET_PLAYLIST_LOADING = "GET_PLAYLIST_LOADING";
export const GET_PLAYLIST_SUCCESS = "GET_PLAYLIST_SUCCESS";
export const GET_PLAYLIST_ERROR = "GET_PLAYLIST_ERROR";
//
export const SET_COLLABORATIVE_LOADING = "SET_COLLABORATIVE_LOADING";
export const SET_COLLABORATIVE_SUCCESS = "SET_COLLABORATIVE_SUCCESS";
export const SET_COLLABORATIVE_ERROR = "SET_COLLABORATIVE_ERROR";
//
export const GET_ALLSESSIONS = "GET_ALLSESSIONS";

export const GET_PLAYLISTTRACKS_LOADING = "GET_PLAYLISTTRACKS_LOADING";
export const GET_PLAYLISTTRACKS_SUCCESS = "GET_PLAYLISTTRACKS_SUCCESS";
export const GET_PLAYLISTTRACKS_ERROR = "GET_PLAYLISTTRACKS_ERROR";


export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';
//
export const SET_LOGGEDIN = "SET_LOGGEDIN";
export const SET_LOGGEDOUT = "SET_LOGGEDOUT";

export const SET_DEVICE_ID = "SET_DEVICE_ID";

//
export const SEARCH_LOADING = "SEARCH_LOADING";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_ERROR = "SEARCH_ERROR";

export const ADD_SONG_LOADING = "ADD_SONG_LOADING";
export const ADD_SONG_SUCCESS = "ADD_SONG_SUCCESS";
export const ADD_SONG_ERROR = "ADD_SONG_ERROR";
export const SET_PLAYSTATE = "SET_PLAYSTATE";

export const REMOVE_SONG_LOADING = "REMOVE_SONG_LOADING";
export const REMOVE_SONG_SUCCESS = "REMOVE_SONG_SUCCESS";
export const REMOVE_SONG_ERROR = "REMOVE_SONG_ERROR";


//
export const CREATE_SESSION_LOADING = "CREATE_SESSION_LOADING";
export const CREATE_SESSION_SUCCESS = "CREATE_SESSION_SUCCESS";
export const CREATE_SESSION_ERROR = "CREATE_SESSION_ERROR";

export const GET_SESSION_LOADING = "GET_SESSION_LOADING";
export const GET_SESSION_SUCCESS = "GET_SESSION_SUCCESS";
export const GET_SESSION_ERROR = "GET_SESSION_ERROR";

