export const GET_PLAYLISTDATA_LOADING = "GET_PLAYLISTDATA_LOADING";
export const GET_PLAYLISTDATA_SUCCESS = "GET_PLAYLISTDATA_SUCCESS";
export const GET_PLAYLISTDATA_ERROR = "GET_PLAYLISTDATA_ERROR";
//
export const CREATE_PLAYLIST_LOADING = "CREATE_PLAYLIST_LOADING";
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS";
export const CREATE_PLAYLIST_ERROR = "CREATE_PLAYLIST_ERROR";


export const GET_USER_LOADING = 'GET_USER_LOADING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';


export const SET_LOGGEDIN_LOADING = "SET_LOGGEDIN_LOADING";
export const SET_LOGGEDIN_SUCCESS = "SET_LOGGEDIN_SUCCESS";
export const SET_LOGGEDIN_ERROR = "SET_LOGGEDIN_ERROR";
//
export const SET_LOGGEDOUT_LOADING = "SET_LOGGEDOUT_LOADING";
export const SET_LOGGEDOUT_SUCCESS = "SET_LOGGEDOUT_SUCCESS";
export const SET_LOGGEDOUT_ERROR = "SET_LOGGEDOUT_ERROR";
